/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/volcano.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Volcano(props) {
  const { nodes, materials } = useGLTF("./models/volcano.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Volcano.geometry}
        material={materials.Rock}
        scale={2}
      />
    </group>
  );
}

useGLTF.preload(".models/volcano.gltf");
